[PHP]
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors = On
error_log = php://stderr
memory_limit = 300M
default_charset = "UTF-8"
date.timezone = "UTC"
extension = mbstring
extension = mysqli
extension = openssl
extension = zip
